version: "3.8"
services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5430:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: person
    volumes:
      - person-data:/var/lib/postgresql/data

  my-app:
    container_name: my-app
    image: spring-student
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/person
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root
    ports:
      - "8090:8090"
    build:
      context: .
    depends_on:
      - db
volumes:
  person-data: {}